#!/bin/bash

wget -P /tmp/ https://github.com/glpi-project/glpi-agent/releases/download/1.5/glpi-agent-1.5-linux-installer.pl

perl /tmp/glpi-agent-1.5-linux-installer.pl -s "glpihmlg.mpes.mp.br" --tag $(hostname -s) --httpd-trust=127.0.0.1/32 --no-ssl-check -l /tmp -Q -v
echo "delaytime=10" >> /etc/glpi-agent/conf.d/00-install.cfg
systemctl restart glpi-agent
glpi-inventory
